print("Jet Francis Q. Podaca")
print("Brgy. Matalaba, Santa Cruz, Marinduque")
print("October 01, 2001")
print("Marinduque State College")
print("BS in Information Technology")
print("2")
print("A")
print("Travelling")
print("Drawing stick figures")
print("Playing online games")
print("Playing recorder")
print("Watching anime")